name: VibeRegionGuard
version: 0.1.2
main: com.vibeprivate.VibePrivatePlugin
api-version: '1.21'
authors:
  - Li2Fox
softdepend:
  - CMI
  - Vault
libraries:
  - org.xerial:sqlite-jdbc:3.49.1.0
  - com.mysql:mysql-connector-j:8.4.0
commands:
  vp:
    description: Opens VibeRegionGuard menu or help.
    usage: /vp [help]
  privat:
    description: Opens VibeRegionGuard menu or help.
    usage: /privat [help]
  privatadmin:
    description: Opens VibeRegionGuard admin menu.
    usage: /privatadmin
  home:
    description: Teleports to your VibeRegionGuard HOME region.
    usage: /home
  sethome:
    description: Sets your VibeRegionGuard HOME teleport point.
    usage: /sethome
permissions:
  vibeprivate.bypass:
    description: Bypass VibeRegionGuard region protection.
    default: op
  vibeprivate.admin:
    description: Access VibeRegionGuard admin tools.
    default: op
